jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Gradle
      run: ./buildAndGenJar.bat ec
    - continue-on-error: true
      name: Update spider jar
      uses: EndBug/add-and-commit@v7
      with:
        add: '[''./jar/custom_spider.jar'', ''./jar/custom_spider.jar.md5'']'
        default_author: github_actions
        message: update spider jar
name: Spider Jar Gen CI
on:
  repository_dispatch:
    types: trigger-ga___genJar.yml
